"""Initial schema

Revision ID: b601872e7e55
Revises: 
Create Date: 2026-05-26 22:55:40.339243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b601872e7e55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternatives_code'), 'alternatives', ['code'], unique=True)
    op.create_index(op.f('ix_alternatives_id'), 'alternatives', ['id'], unique=False)
    op.create_table('criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('Cost', 'Benefit', name='criteriatypeenum'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criteria_code'), 'criteria', ['code'], unique=True)
    op.create_index(op.f('ix_criteria_id'), 'criteria', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('IT_Admin', 'Verificator', 'Data_Admin', name='roleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ahp_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix_data', sa.JSON(), nullable=True),
    sa.Column('cr_value', sa.Float(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ahp_status_id'), 'ahp_status', ['id'], unique=False)
    op.create_table('decision_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alternative_id', sa.Integer(), nullable=False),
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['alternative_id'], ['alternatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criteria_id'], ['criteria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alternative_id', 'criteria_id', name='_alt_crit_uc')
    )
    op.create_index(op.f('ix_decision_matrix_id'), 'decision_matrix', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('marcos_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alternative_id', sa.Integer(), nullable=False),
    sa.Column('utility_k_minus', sa.Float(), nullable=False),
    sa.Column('utility_k_plus', sa.Float(), nullable=False),
    sa.Column('utility_f', sa.Float(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alternative_id'], ['alternatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcos_results_id'), 'marcos_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marcos_results_id'), table_name='marcos_results')
    op.drop_table('marcos_results')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_decision_matrix_id'), table_name='decision_matrix')
    op.drop_table('decision_matrix')
    op.drop_index(op.f('ix_ahp_status_id'), table_name='ahp_status')
    op.drop_table('ahp_status')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_criteria_id'), table_name='criteria')
    op.drop_index(op.f('ix_criteria_code'), table_name='criteria')
    op.drop_table('criteria')
    op.drop_index(op.f('ix_alternatives_id'), table_name='alternatives')
    op.drop_index(op.f('ix_alternatives_code'), table_name='alternatives')
    op.drop_table('alternatives')
    # ### end Alembic commands ###
